#pragma once

// From glfw3.h
#define DANK_MOUSE_BUTTON_1         0
#define DANK_MOUSE_BUTTON_2         1
#define DANK_MOUSE_BUTTON_3         2
#define DANK_MOUSE_BUTTON_4         3
#define DANK_MOUSE_BUTTON_5         4
#define DANK_MOUSE_BUTTON_6         5
#define DANK_MOUSE_BUTTON_7         6
#define DANK_MOUSE_BUTTON_8         7
#define DANK_MOUSE_BUTTON_LAST      DANK_MOUSE_BUTTON_8
#define DANK_MOUSE_BUTTON_LEFT      DANK_MOUSE_BUTTON_1
#define DANK_MOUSE_BUTTON_RIGHT     DANK_MOUSE_BUTTON_2
#define DANK_MOUSE_BUTTON_MIDDLE    DANK_MOUSE_BUTTON_3 